server:
  port: 8099

swagger:
  swagger-ui-open: true

file:
  inPathParent: E:\文档\test\in\
  outPathParent: E:\文档\test\out\
  errorPathParent: E:\文档\test\error\

ftp:
  host: 192.168.0.143
  port: 21
  username: xiaojun
  password: xiaojun123456

scheduled:
#  每5秒
  cron: 0/5 * * * * ?

spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

mongodb:
  downloadPath: E:\文档\test2\11\
